version: '3.8'
services:
  tareas:
    image: tareas
    ports:
      - "8080:80"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DB: ${SPRING_DATASOURCE_DB}
    volumes:
      - ./src:/tarea/src
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0
    environment:
     SPRING_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
     SPRING_DATASOURCE: ${SPRING_DATASOURCE_DB}
    ports:
     - "3310:3006"
    volumes:
    - data_base:/var/lib/mysql
    networks:
     - default

volumes:
  data_base:
networks:
 default:
  driver: bridge